### ISSUE TITLE
Forbid sending objects with missing or unexpected keys

### ISSUE THREAD

**Issue by bettio** [astarte-platform/astarte-device-sdk-java#27]
astarte-device-sdk-java must raise an exception when trying to send an object with missing/null keys or unexpected keys.

Invalid objects must be rejected before sending them to Astarte in order to avoid client disconnection.

Following 2 steps must be done:
- [ ] Check whether invalid objects are already handled
- [ ] Implement exception raising code if needed

**Comment by naveenfunk** [comment]
@bettio do you know how to send object using a property type interface ?
